{
    'name': 'CollageManagment',
    'summary': 'This Module For Collage',
    'license': 'AGPL-3',
    'category': 'Extra Tools',
    'sequence': '13',
    'depends': [
        'base',
        'openeducat_activity',
        'openeducat_admission',
        'openeducat_assignment',
        'openeducat_attendance',
        'openeducat_classroom',
        'openeducat_core',
        'openeducat_erp',
        'openeducat_exam',
        'openeducat_facility',
        'openeducat_fees',
        'openeducat_library',
        'openeducat_parent',
        'openeducat_timetable',
        'web_openeducat',
    ],
    'demo': [],
    'data': [
        # 'security/security_rules.xml',
        'security/ir.model.access.csv',
        'views/doctor_sheet.xml',
        'views/inherit_op_student.xml',
        'views/inherit_op_subject.xml',
        'views/menus.xml',
    ],
}
